services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
    restart: unless-stopped
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./users.xml:/etc/clickhouse-server/users.d/users.xml

volumes:
  clickhouse_data:
